# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "secondary" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Write a if condition for main and secondary branch
      - uses: actions/checkout@v2
      if: ${GITHUB_REF} == "refs/heads/main"
        - name: Execute ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: 3.108.217.47
          username: ec2-user
          key: ${{ secrets.WORKFLOW_SECRET }}
          port: 22
          timeout: 10m
          script: | #!/bin/bash
            cd test/workflow-test/
            git fetch
            git pull
            npm install
            pm2 start app1.json
      else:
        - name: "Checkout secondary branch"
          run: checkout
        

