# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-127-6-4.ap-south-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.WORKFLOW_SECRET }}
          port: 22
          timeout: 60
          script: sh ../../run.sh

