# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "secondary" ]

jobs:
  build:
    if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      steps:
        - name: Execute ssh commands
          uses: appleboy/ssh-action@master
          with:
            host: 3.108.217.47
            username: ec2-user
            key: ${{ secrets.WORKFLOW_SECRET }}
            port: 22
            timeout: 10m
            script: | #!/bin/bash
              cd test/workflow-test/
              git fetch
              git pull
              npm install
              pm2 start app1.json
    if: github.ref == 'refs/heads/secondary'
      runs-on: ubuntu-latest
      steps:
        - name: Execute ssh commands
          uses: appleboy/ssh-action@master
          with:
            host: 3.108.217.47
            username: ec2-user
            key: ${{ secrets.WORKFLOW_SECRET }}
            port: 22
            timeout: 10m
            script: | #!/bin/bash
              cd test/workflow-test/
              git fetch
              git pull
              npm install
              pm2 start app2.json
        

