# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "secondary" ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Execute ssh commands (main)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: 3.110.189.140
          username: ec2-user
          key: ${{ secrets.WORKFLOW_SECRET }}
          port: 22
          timeout: 10m
          script: sh run_app1.sh   
            
      - name: Execute ssh commands (secondary)
        if: github.ref == 'refs/heads/secondary'
        uses: appleboy/ssh-action@master
        with:
          host: 3.110.189.140
          username: ec2-user
          key: ${{ secrets.WORKFLOW_SECRET }}
          port: 22
          timeout: 10m
          script: sh run_app2.sh  
            
        
  

        

